"""v3_add_table_name_relationships_drop_records

Revision ID: 4939b7b88b58
Revises: 4d60e9f1c910
Create Date: 2026-07-29 00:53:38.343872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4939b7b88b58'
down_revision: Union[str, Sequence[str], None] = '4d60e9f1c910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('table_name', sa.String(), nullable=False, server_default=''))
    op.create_unique_constraint('uq_datasets_table_name', 'datasets', ['table_name'])
    op.alter_column('datasets', 'table_name', server_default=None)
    
    op.create_table('relationships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_dataset_id', sa.Integer(), nullable=False),
        sa.Column('source_column', sa.String(), nullable=False),
        sa.Column('target_dataset_id', sa.Integer(), nullable=False),
        sa.Column('target_column', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.id'], ),
        sa.ForeignKeyConstraint(['target_dataset_id'], ['datasets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)

    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dataset_id', sa.Integer(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_table('relationships')
    
    op.drop_constraint('uq_datasets_table_name', 'datasets', type_='unique')
    op.drop_column('datasets', 'table_name')
    # ### end Alembic commands ###
